### ISSUE TITLE
更换更快网址

### ISSUE THREAD

**Issue by coppea** [missuo/Telegraph-Image-Hosting#2]
https://missuo.ru/file/d35fe694c8526782c0fc5.png
替换为
https://i3.wp.com/telegra.ph/file/d35fe694c8526782c0fc5.png

使用wp代理，速度更快

**Comment by missuo** [comment]
> https://missuo.ru/file/d35fe694c8526782c0fc5.png
> 
> 替换为
> 
> https://i3.wp.com/telegra.ph/file/d35fe694c8526782c0fc5.png
> 
> 
> 
> 使用wp代理，速度更快

为了安全和可靠性，不会使用任何第三方加速代理。

**Comment by coppea** [comment]
好的，欠考虑，没想到这点
