### ISSUE TITLE
SSL certificate has expired

### ISSUE THREAD

**Issue by s1204IT** [missuo/Telegraph-Image-Hosting#5]
![](https://github.com/missuo/Telegraph-Image-Hosting/assets/52069677/98c0f576-61ef-490a-b144-1b9652035837)

**Comment by missuo** [comment]
> ![](https://github.com/missuo/Telegraph-Image-Hosting/assets/52069677/98c0f576-61ef-490a-b144-1b9652035837)
> 
> 

I will fix it. Thanks for your feedback.
